// packages/svelte/src/lib/StaticMap.svelte
<script lang="ts">
	import { createStaticMap, type StaticMapOptions, type StaticMapsState } from '@staticmaps/core';

	export let options: StaticMapOptions;

	let { width, height, viewBox, tiles, multiPolygons } = {} as StaticMapsState;

	$: {
		({ width, height, viewBox, tiles, multiPolygons } = createStaticMap(options));
		console.log('updates', width, height);
	}
</script>

<svg {width} {height} {viewBox}>
	{#each tiles as tile}
		<image {...tile} />
	{/each}
	{#each multiPolygons as multiPolygon}
		<path {...multiPolygon} vector-effect="non-scaling-stroke" />
	{/each}
</svg>

// packages/vue/src/StaticMap.vue
<script setup lang="ts">
import { StaticMapsState, StaticMapOptions, createStaticMap } from '@staticmaps/core';

const props = defineProps<{ options: StaticMapOptions }>();
const o = createStaticMap(props.options);
</script>

<template>
  <svg :width="o.width" :height="o.height" :viewBox="o.viewBox">
    <image v-for="tile in o.tiles" v-bind="tile"></image>
    <path v-for="multiPolygon in o.multiPolygons" v-bind="multiPolygon" vectorEffect="non-scaling-stroke"></path>
  </svg>
  <div>Hello</div>
</template>
